// The campaign: 15 environment chapters plus the epilogue, exactly as the
// Section 3 table lays them out, with the Section 3 transition plan encoded as
// `bridgeIn` / `bridgeOut` so every chapter opens on remnants of the last one
// and closes by foreshadowing the next.
//
// `beats` follow the Section 3 chapter pacing template:
//   arrival - teach - test - rest - twist - climax - departure
// Lengths are in tiles and were chosen so a chapter reads at roughly the
// minute counts the template gives.

export const ACT_OF = { 1: [0, 4], 2: [5, 8], 3: [9, 11], 4: [12, 13], 5: [14, 15] };

export function actFor(index) {
  for (const [act, [a, b]] of Object.entries(ACT_OF)) {
    if (index >= a && index <= b) return Number(act);
  }
  return 1;
}

export const CHAPTERS = [
  {
    id: 'ch0', num: '0', name: 'The Last Village', biome: 'high_forest',
    fragments: 1,
    seed: 'crownless/high-forest/last-village',
    ambience: 'forest', surface: 'grass', accent: '#c8a24a',
    sky: '#2b3a52', skyBottom: '#5c6b7a',
    tutorial: true,
    intro: 'The bell is quiet. The road is not where you left it.',
    outro: 'Evening comes early under the waking trees.',
    purpose: 'Teach movement, attack, damage, healing and waystones.',
    enemies: ['snail', 'bee', 'boar'],
    climax: { kind: 'elite', enemy: 'wild_boar', name: 'The Road Boar' },
    bridgeOut: 'Healthy trees thin out; evening colours creep in two screens early.',
    beats: [
      { type: 'arrival', len: 30, safe: true },
      { type: 'teach', len: 34, teach: 'jump' },
      { type: 'teach', len: 30, teach: 'attack' },
      { type: 'test', len: 38, enemy: 'snail' },
      { type: 'rest', len: 20, waystone: 'wake' },
      { type: 'test', len: 40, enemy: 'bee' },
      { type: 'twist', len: 36, side: true },
      { type: 'climax', len: 44 },
      { type: 'departure', len: 22 },
    ],
  },
  {
    id: 'ch1', num: '1', name: 'The Waking Trees', biome: 'dusk_wood',
    fragments: 2,
    seed: 'crownless/dusk-wood/waking-trees',
    ambience: 'forest', surface: 'grass', accent: '#8a6fd0',
    sky: '#221d3a', skyBottom: '#3d3357',
    haze: 0.26,
    intro: 'Four layers of forest, and something moving in all of them.',
    outro: 'The paths begin to disagree with each other.',
    purpose: 'Four-layer depth; charged boar lanes and falling branch hazards.',
    enemies: ['boar', 'bee', 'snail'],
    hazard: 'falling',
    climax: { kind: 'elite', enemy: 'wild_boar', name: 'Lane Warden' },
    bridgeIn: 'The same ground silhouette as High Forest, under a changed canopy.',
    bridgeOut: 'Paths split around repeated dead trees and corrupted roots.',
    beats: [
      { type: 'arrival', len: 26 },
      { type: 'teach', len: 34, teach: 'hazard' },
      { type: 'test', len: 44, enemy: 'boar' },
      { type: 'rest', len: 18, waystone: 'lane' },
      { type: 'twist', len: 44, side: true },
      { type: 'test', len: 38, enemy: 'bee' },
      { type: 'climax', len: 42 },
      { type: 'departure', len: 20 },
    ],
  },
  {
    id: 'ch2', num: '2', name: 'Where Paths Forget', biome: 'lost_glades',
    fragments: 2,
    seed: 'crownless/lost-glades/paths-forget',
    ambience: 'forest', surface: 'grass', accent: '#6fd0a8',
    sky: '#16241f', skyBottom: '#2c4136',
    haze: 0.3,
    intro: 'You have walked this clearing before. You are sure of it.',
    outro: 'Stone markers begin where the trail signs end.',
    purpose: 'Looping routes, false landmarks and the first hidden-road Vow.',
    enemies: ['snail', 'bee', 'boar'],
    reward: { vow: 'bells' },
    bridgeIn: 'Dusk Wood roots continue into the first glade screen.',
    bridgeOut: 'Trail markers thicken into grave markers; fog replaces canopy.',
    beats: [
      { type: 'arrival', len: 26 },
      { type: 'teach', len: 32, teach: 'route' },
      { type: 'twist', len: 46, side: true },
      { type: 'rest', len: 18, waystone: 'glade' },
      { type: 'test', len: 44, enemy: 'bee' },
      { type: 'twist', len: 40, side: true },
      { type: 'climax', len: 34 },
      { type: 'departure', len: 20 },
    ],
  },
  {
    id: 'ch3', num: '3', name: 'Graves Under Rain', biome: 'cemetery',
    fragments: 2,
    seed: 'crownless/cemetery/graves-under-rain',
    ambience: 'wind', surface: 'stone', accent: '#d0704f',
    sky: '#2a1c24', skyBottom: '#4a3038',
    weather: 'rain',
    intro: 'Every name here is worn to the same three letters.',
    outro: 'The graves become military memorials, and the wall begins.',
    purpose: 'Skeleton debut; a deliberate transition from roots to masonry.',
    enemies: ['skeleton', 'snail', 'bee'],
    climax: { kind: 'arena', enemies: ['skeleton', 'skeleton', 'snail'] },
    bridgeIn: 'Roots run through the first cemetery screen, binding both packs.',
    bridgeOut: 'Distant houses and mountain silhouettes before any masonry.',
    beats: [
      { type: 'arrival', len: 28 },
      { type: 'teach', len: 34, teach: 'enemy', enemy: 'skeleton' },
      { type: 'test', len: 42, enemy: 'skeleton' },
      { type: 'rest', len: 18, waystone: 'grave' },
      { type: 'twist', len: 42, side: true },
      { type: 'climax', len: 40 },
      { type: 'departure', len: 22 },
    ],
  },
  {
    id: 'ch4', num: '4', name: 'The Closed Gate', biome: 'fortress',
    fragments: 2,
    seed: 'crownless/fortress/closed-gate',
    ambience: 'wind', surface: 'stone', accent: '#e0c078',
    sky: '#1d2636', skyBottom: '#46516b',
    intro: 'The capital has a door. It is not going to open.',
    outro: 'They take your sword first. They always do.',
    purpose: 'Civic remnants; first major set piece and a failed entry.',
    enemies: ['skeleton', 'boar', 'boar_warrior'],
    boss: 'gate_warden',
    bridgeIn: 'Grave markers become civic memorials beneath the walls.',
    bridgeOut: 'A failed gate set piece ends in capture, under twenty seconds.',
    beats: [
      { type: 'arrival', len: 28 },
      { type: 'teach', len: 32, teach: 'enemy', enemy: 'boar_warrior' },
      { type: 'test', len: 44, enemy: 'skeleton' },
      { type: 'rest', len: 18, waystone: 'gate' },
      { type: 'twist', len: 44, side: true },
      { type: 'boss', len: 40 },
      { type: 'departure', len: 20 },
    ],
  },
  {
    id: 'ch5', num: '5', name: 'Below the Crown', biome: 'prison',
    fragments: 2,
    seed: 'crownless/prison/below-the-crown',
    ambience: 'hall', surface: 'stone', accent: '#7fd0e0',
    sky: '#0f1218', skyBottom: '#1b222c',
    strip: true,                 // opens with the sword and Vows taken away
    intro: 'No sword. No vows. A door that was never meant to be opened inward.',
    outro: 'The drainage wall has been weak for a long time.',
    purpose: 'Captured opening, temporary loss of upgrades, regain-the-sword arc.',
    enemies: ['skeleton_jailer', 'skeleton', 'slime'],
    climax: { kind: 'arena', enemies: ['skeleton_jailer', 'skeleton_jailer', 'skeleton'] },
    bridgeIn: 'You wake in a cell, disarmed, with the fortress above you.',
    bridgeOut: 'A broken drainage wall becomes the escape route.',
    beats: [
      { type: 'arrival', len: 26, safe: true },
      { type: 'teach', len: 34, teach: 'unarmed' },
      { type: 'rest', len: 18, waystone: 'cell', restore: true },
      { type: 'test', len: 44, enemy: 'skeleton_jailer' },
      { type: 'twist', len: 42, side: true },
      { type: 'climax', len: 38 },
      { type: 'departure', len: 22 },
    ],
  },
  {
    id: 'ch6', num: '6', name: 'The Black Water', biome: 'sewers',
    fragments: 2,
    seed: 'crownless/sewers/black-water',
    ambience: 'water', surface: 'stone', accent: '#7fc46a',
    sky: '#0d1410', skyBottom: '#18251c',
    intro: 'The fortress throws everything down here eventually.',
    outro: 'The channel widens, and the air tastes of salt.',
    purpose: 'Slime den, drainage machinery and rising water.',
    enemies: ['slime', 'slime_toxic', 'skeleton', 'snail'],
    hazard: 'water',
    climax: { kind: 'arena', enemies: ['slime_toxic', 'slime_toxic', 'skeleton'] },
    bridgeIn: 'Prison bricks, chains and grates carry into the first sewer room.',
    bridgeOut: 'Drip becomes surf; green water becomes violet tide.',
    beats: [
      { type: 'arrival', len: 26 },
      { type: 'teach', len: 32, teach: 'enemy', enemy: 'slime' },
      { type: 'test', len: 44, enemy: 'slime_toxic' },
      { type: 'rest', len: 18, waystone: 'canal' },
      { type: 'twist', len: 46, side: true, rising: true },
      { type: 'climax', len: 36 },
      { type: 'departure', len: 22 },
    ],
  },
  {
    id: 'ch7', num: '7', name: 'The Violet Tide', biome: 'purple_bay',
    fragments: 2,
    seed: 'crownless/purple-bay/violet-tide',
    ambience: 'water', surface: 'stone', accent: '#c88ae0',
    sky: '#3a2a55', skyBottom: '#8a6f9e',
    intro: 'Open sky, for the first time in a long while.',
    outro: 'The coast softens into reeds, then into mud.',
    purpose: 'Sea platforms, tidal caves and a broad visual breath.',
    enemies: ['crab', 'slime_tide', 'bee'],
    climax: { kind: 'arena', enemies: ['crab', 'crab', 'slime_tide'] },
    bridgeIn: 'Washed-up fortress debris on the first beach.',
    bridgeOut: 'Open-sea depth drops away; wet reflections stay.',
    beats: [
      { type: 'arrival', len: 30, safe: true },
      { type: 'teach', len: 32, teach: 'enemy', enemy: 'crab' },
      { type: 'test', len: 44, enemy: 'crab' },
      { type: 'rest', len: 20, waystone: 'tide' },
      { type: 'twist', len: 44, side: true },
      { type: 'climax', len: 36 },
      { type: 'departure', len: 20 },
    ],
  },
  {
    id: 'ch8', num: '8', name: 'The Sinking Road', biome: 'swamp',
    fragments: 2,
    seed: 'crownless/swamp/sinking-road',
    ambience: 'water', surface: 'mud', accent: '#9adf5a',
    sky: '#1a2418', skyBottom: '#33422a',
    intro: 'The road is still here. It is just under something now.',
    outro: 'A derelict pumping station, and the first straight rail in weeks.',
    purpose: 'Mud, poison pools and platforms that telegraph sinking.',
    enemies: ['slime_toxic', 'bee_swamp', 'crab'],
    hazard: 'poison',
    boss: 'saint_mire',
    bridgeIn: 'Reed-filled estuary before any real mud.',
    bridgeOut: 'Marsh water still sits below the first mine platforms.',
    beats: [
      { type: 'arrival', len: 26 },
      { type: 'teach', len: 34, teach: 'sinking' },
      { type: 'test', len: 42, enemy: 'slime_toxic' },
      { type: 'rest', len: 18, waystone: 'mire' },
      { type: 'twist', len: 44, side: true },
      { type: 'boss', len: 40 },
      { type: 'departure', len: 20 },
    ],
  },
  {
    id: 'ch9', num: '9', name: 'The Empty Shift', biome: 'mine',
    fragments: 2,
    seed: 'crownless/mine/empty-shift',
    ambience: 'cave', surface: 'stone', accent: '#e0a050',
    sky: '#14100c', skyBottom: '#241c14',
    haze: 0.46,
    intro: 'The lamps are still lit. Nobody left in a hurry.',
    outro: 'The supports stop. The rock does not.',
    // Recorded in docs/asset_issues.md: the Lonely Mine tileset is forest
    // material, so this chapter is an abandoned worksite being reclaimed by
    // growth, with the machinery carried by the background and foreground.
    purpose: 'Abandoned worksite, lifts and route-choice built from what the pack has.',
    enemies: ['slime', 'bee', 'skeleton'],
    climax: { kind: 'arena', enemies: ['skeleton', 'slime', 'slime'] },
    bridgeIn: 'The first screen still has marsh water under the platforms.',
    bridgeOut: 'Lighting changes before the collision language does.',
    beats: [
      { type: 'arrival', len: 26 },
      { type: 'teach', len: 34, teach: 'route' },
      { type: 'test', len: 42, enemy: 'slime' },
      { type: 'rest', len: 18, waystone: 'shaft' },
      { type: 'twist', len: 46, side: true },
      { type: 'climax', len: 36 },
      { type: 'departure', len: 22 },
    ],
  },
  {
    id: 'ch10', num: '10', name: 'The Kingdom Beneath', biome: 'deep_cave',
    fragments: 2,
    seed: 'crownless/deep-cave/kingdom-beneath',
    ambience: 'cave', surface: 'stone', accent: '#8ab0e0',
    sky: '#07090f', skyBottom: '#12161f',
    haze: 0.34,
    vertical: true,
    dark: 0.55,
    intro: 'Down is the only direction that still agrees with itself.',
    outro: 'A long shaft, and wind coming the wrong way up it.',
    purpose: 'Vertical descent, darkness rhythm and crystal navigation.',
    enemies: ['slime', 'slime_toxic', 'bee'],
    climax: { kind: 'arena', enemies: ['slime_toxic', 'slime_toxic', 'bee'] },
    bridgeIn: 'Timber supports thin out and stop.',
    bridgeOut: 'Cave rock survives into the pass\'s first sheltered alcove.',
    beats: [
      { type: 'arrival', len: 26 },
      { type: 'teach', len: 32, teach: 'dark' },
      { type: 'test', len: 44, enemy: 'slime_toxic' },
      { type: 'rest', len: 18, waystone: 'deep' },
      { type: 'twist', len: 46, side: true },
      { type: 'climax', len: 36 },
      { type: 'departure', len: 24 },
    ],
  },
  {
    id: 'ch11', num: '11', name: 'The Bone Mountains', biome: 'deadwind',
    fragments: 2,
    seed: 'crownless/deadwind/bone-mountains',
    ambience: 'wind', surface: 'stone', accent: '#b8d0e0',
    sky: '#1b2430', skyBottom: '#49606f',
    hazard: 'wind',
    intro: 'The wind here has opinions about where you should stand.',
    outro: 'Carved stairs, and a doorway that should not fit the mountain.',
    purpose: 'Gust timing, bone landmarks and the boar warrior as road guard.',
    enemies: ['boar_pass', 'boar_warrior', 'skeleton'],
    boss: 'bone_colossus',
    bridgeIn: 'A long upward shaft opens into wind and distant cliffs.',
    bridgeOut: 'Temple geometry appears as silhouettes before the threshold.',
    beats: [
      { type: 'arrival', len: 26 },
      { type: 'teach', len: 34, teach: 'wind' },
      { type: 'test', len: 44, enemy: 'boar_pass' },
      { type: 'rest', len: 18, waystone: 'pass' },
      { type: 'twist', len: 44, side: true },
      { type: 'boss', len: 42 },
      { type: 'departure', len: 20 },
    ],
  },
  {
    id: 'ch12', num: '12', name: 'The First Crown', biome: 'temple',
    fragments: 2,
    seed: 'crownless/temple/first-crown',
    ambience: 'hall', surface: 'stone', accent: '#7fe0c8',
    sky: '#0d1a1c', skyBottom: '#1c3033',
    haze: 0.3,
    intro: 'The bell was cast here. So was the silence.',
    outro: 'The later copies are downhill, and they are painted red.',
    purpose: 'Puzzle-combat gauntlet and the truth behind the Crown Bell.',
    enemies: ['skeleton', 'boar_warrior', 'slime'],
    reward: { crest: 'bell' },
    climax: { kind: 'arena', enemies: ['boar_warrior', 'skeleton', 'skeleton'] },
    bridgeIn: 'Bone markers and carved stairs lead to an impossible doorway.',
    bridgeOut: 'Ancient bell symbols become later religious copies.',
    beats: [
      { type: 'arrival', len: 26 },
      { type: 'teach', len: 34, teach: 'mechanism' },
      { type: 'test', len: 44, enemy: 'skeleton' },
      { type: 'rest', len: 18, waystone: 'crown' },
      { type: 'twist', len: 46, side: true },
      { type: 'climax', len: 40 },
      { type: 'departure', len: 20 },
    ],
  },
  {
    id: 'ch13', num: '13', name: 'The Red Silence', biome: 'monastery',
    fragments: 1,
    seed: 'crownless/monastery/red-silence',
    ambience: 'hall', surface: 'stone', accent: '#e05a5a',
    sky: '#1a0e12', skyBottom: '#3a1e22',
    intro: 'They kept the shape of the bell and threw away its voice.',
    outro: 'A covered bridge, and a house at the end of it.',
    purpose: 'Ritual approach, scarlet language, bell mechanisms.',
    enemies: ['skeleton_acolyte', 'skeleton', 'boar_warrior'],
    boss: 'voiceless_bell',
    bridgeIn: 'One recurring red accent ties the temple to its copy.',
    bridgeOut: 'No portal: the mansion must feel physically reachable.',
    beats: [
      { type: 'arrival', len: 26 },
      { type: 'teach', len: 32, teach: 'ritual' },
      { type: 'test', len: 44, enemy: 'skeleton_acolyte' },
      { type: 'rest', len: 18, waystone: 'silence' },
      { type: 'twist', len: 44, side: true },
      { type: 'boss', len: 42 },
      { type: 'departure', len: 20 },
    ],
  },
  {
    id: 'ch14', num: '14', name: "The Usurper's House", biome: 'mansion',
    fragments: 1,
    seed: 'crownless/mansion/usurpers-house',
    ambience: 'hall', surface: 'stone', accent: '#e0405a',
    sky: '#140a10', skyBottom: '#2e1420',
    intro: 'Someone has been keeping the lamps lit for a guest.',
    outro: 'The bell has a voice again. It is yours.',
    purpose: 'Finale; revisited motifs from every act and the Blood Regent.',
    enemies: ['skeleton_acolyte', 'boar_warrior', 'skeleton'],
    boss: 'blood_regent',
    bridgeIn: 'A covered bridge from sanctuary to royal residence.',
    bridgeOut: 'The road, lit, all the way back.',
    beats: [
      { type: 'arrival', len: 26 },
      { type: 'teach', len: 32, teach: 'ritual' },
      { type: 'test', len: 44, enemy: 'boar_warrior' },
      { type: 'rest', len: 18, waystone: 'house' },
      { type: 'twist', len: 46, side: true },
      { type: 'boss', len: 44 },
      { type: 'departure', len: 18 },
    ],
  },
  {
    id: 'chE', num: 'E', name: 'Road Rekindled', biome: 'high_forest',
    fragments: 0,
    seed: 'crownless/high-forest/road-rekindled',
    ambience: 'forest', surface: 'grass', accent: '#ffd97a',
    sky: '#4a6a86', skyBottom: '#9ab4c4',
    epilogue: true,
    intro: 'The trees are the same. The light is not.',
    outro: '',
    purpose: 'Short revisit with restored colour and non-combat closure.',
    enemies: [],
    beats: [
      { type: 'arrival', len: 30, safe: true },
      { type: 'rest', len: 22, waystone: 'home' },
      { type: 'departure', len: 30, safe: true },
    ],
  },
];

export const BY_ID = Object.fromEntries(CHAPTERS.map((c, i) => [c.id, { ...c, index: i }]));
export function chapterAt(i) { return CHAPTERS[Math.max(0, Math.min(CHAPTERS.length - 1, i))]; }
export function nextChapterId(id) {
  const i = CHAPTERS.findIndex((c) => c.id === id);
  return i >= 0 && i < CHAPTERS.length - 1 ? CHAPTERS[i + 1].id : null;
}

// Waystone lines. Section 2: one or two short sentences beat repeated dialogue.
export const WAYSTONE_LINES = {
  wake: 'You were carrying something. It is still warm.',
  lane: 'The trees lean the way the road used to run.',
  glade: 'Three markers. All of them say the same distance.',
  grave: 'The stones remember longer than the names do.',
  gate: 'They barred it from the inside. That took time.',
  cell: 'Someone left the sword where you would find it.',
  canal: 'Everything the fortress denies ends up down here.',
  tide: 'Salt, and the first horizon in months.',
  mire: 'The road is under this. Step where it was.',
  shaft: 'The shift never ended. It was simply not returned to.',
  deep: 'No supports now. Only the weight, agreeing to hold.',
  pass: 'Bones point the way. They were pointing at something.',
  crown: 'The first bell was cast here, and heard once.',
  silence: 'They kept the shape and threw away the voice.',
  house: 'The lamps were lit for a guest. You will do.',
  home: 'The road is lit the whole way back.',
};
